arm64: smp: Extend visibility of update_ipi_history()
update_ipi_history() is a static void function at lpm-levels.
Since we want to use the function at arch/arm64/kernel/smp.c to
update IPI history, the function needs to be exported as a symbol
from lpm-levels.c and needs to be made visible using the extern
keyword. The function can't be kept static anymore. Thus, extend
its visibility and fix the following compilation error:

../arch/arm64/kernel/smp.c:966:3: error: implicit declaration of function 'update_ipi_history' [-Werror,-Wimplicit-function-declaration]
                update_ipi_history(cpu);
                ^

Fixes: 17981ef38f ("cpuidle: Update IPI history when waking CPUs up with IPIs")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>